# Generated by Django 2.2 on 2020-11-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PetModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pet_image', models.ImageField(upload_to='img')),
                ('desc', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'petposts',
            },
        ),
    ]
