# Generated by Django 2.2 on 2021-01-31 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PetFoodModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodname', models.CharField(max_length=200)),
                ('food_image', models.ImageField(upload_to='img')),
                ('food_price', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'petfoodposts',
            },
        ),
        migrations.CreateModel(
            name='PetModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pet_image', models.ImageField(upload_to='img')),
                ('price', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'petposts',
            },
        ),
        migrations.CreateModel(
            name='PetToyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toyname', models.CharField(max_length=200)),
                ('toy_image', models.ImageField(upload_to='img')),
                ('toy_price', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'pettoyposts',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petfoods', models.ManyToManyField(blank=True, to='shopapp.PetFoodModel')),
                ('pets', models.ManyToManyField(blank=True, to='shopapp.PetModel')),
                ('pettoys', models.ManyToManyField(blank=True, to='shopapp.PetToyModel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'profiles',
            },
        ),
        migrations.CreateModel(
            name='Cartitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('petfoods', models.ManyToManyField(blank=True, to='shopapp.PetFoodModel')),
                ('pets', models.ManyToManyField(blank=True, to='shopapp.PetModel')),
                ('pettoys', models.ManyToManyField(blank=True, to='shopapp.PetToyModel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cart',
                'verbose_name_plural': 'carts',
            },
        ),
    ]
