# Generated by Django 2.2 on 2020-12-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetFoodModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Foodname', models.CharField(max_length=200)),
                ('Food_image', models.ImageField(upload_to='img')),
                ('food_price', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'petposts',
            },
        ),
        migrations.CreateModel(
            name='PetToyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toyname', models.CharField(max_length=200)),
                ('toy_image', models.ImageField(upload_to='img')),
                ('toy_price', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'petposts',
            },
        ),
        migrations.RenameField(
            model_name='petmodel',
            old_name='desc',
            new_name='price',
        ),
    ]
