# Generated by Django 2.2 on 2020-12-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0004_auto_20201206_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pettoymodel',
            name='toy_image',
            field=models.ImageField(upload_to='img'),
        ),
    ]
