# Generated by Django 2.2 on 2020-12-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='name',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
